@WebApplication1_HostAddress = http://localhost:5120

GET {{WebApplication1_HostAddress}}/weatherforecast/
Accept: application/json

### refreshToken
### eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIwMTQ3OTY5MC1jMTUxLTRhNjItOWZjMy0yOTBhMWQxMjJkMWUiLCJlbWFpbCI6InBkYUBwZGEucGRhIiwiZ2l2ZW5fbmFtZSI6InBkYSIsInJvbGUiOiJVc2VyIiwibmJmIjoxNzI4NzU3OTg2LCJleHAiOjE3MjkzNjI3ODYsImlhdCI6MTcyODc1Nzk4NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTIwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTIwIn0.Za6jqoJX9WVuSApSTjY8Gru8XcOj1wqKABJEhoAOYmdBLRbTMwhPNcHgkEGq5elcNIrTWZqiKC11PYfsaXNSRQ
### accessToken
### eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjkzNjI3ODYsIm5iZiI6MTcyODc1Nzk4NiwiaWF0IjoxNzI4NzU3OTg2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxMjAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxMjAifQ.dkXtiRguoV1Et6s_mqbg-XHxWC2DjAP0uRsNht0u-qzlE08LDWPdhUA6rV3F7t4ZN_3LLgIcf5BI_K1h5hS6FQ