// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.model.CoffeModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Coffes");
                });

            modelBuilder.Entity("WebApplication1.model.CoffeSizeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("CoffeSizes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createAt = new DateTime(2024, 10, 2, 9, 18, 31, 980, DateTimeKind.Utc).AddTicks(7050),
                            name = "S",
                            updateAt = new DateTime(2024, 10, 2, 9, 18, 31, 997, DateTimeKind.Utc).AddTicks(2620)
                        },
                        new
                        {
                            id = 2,
                            createAt = new DateTime(2024, 10, 2, 9, 18, 31, 997, DateTimeKind.Utc).AddTicks(3350),
                            name = "M",
                            updateAt = new DateTime(2024, 10, 2, 9, 18, 31, 997, DateTimeKind.Utc).AddTicks(3350)
                        },
                        new
                        {
                            id = 3,
                            createAt = new DateTime(2024, 10, 2, 9, 18, 31, 997, DateTimeKind.Utc).AddTicks(3350),
                            name = "L",
                            updateAt = new DateTime(2024, 10, 2, 9, 18, 31, 997, DateTimeKind.Utc).AddTicks(3350)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
